//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SALONES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudes
    {
        public int id_solicitud { get; set; }
        public int id_cliente { get; set; }
        public System.DateTime fecha_evento { get; set; }
        public int cant_personas { get; set; }
        public int id_motivo { get; set; }
        public string observaciones { get; set; }
        public int id_estado { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual estado estado { get; set; }
        public virtual motivo motivo { get; set; }
    }
}
