//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SALONES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_clientes
    {
        public int id_cliente { get; set; }
        public string identificacion { get; set; }
        public string nombre_completo { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string departamento { get; set; }
        public string ciudad { get; set; }
        public int edad { get; set; }
    }
}
